version: '3.7'

networks:
  streamx-net:
    driver: bridge

services:

  streamx-zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - streamx-net

  streamx-kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9094:9094"
    links:
      - streamx-zookeeper
    networks:
      - streamx-net
    environment:
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "movies:1:1"
      KAFKA_ZOOKEEPER_CONNECT: streamx-zookeeper:2181
