version: '3.7'

networks:
  streamx-net:
    driver: bridge

services:

  streamx-zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - streamx-net

  streamx-kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
      - "29092:29092"
    links:
      - streamx-zookeeper
    networks:
      - streamx-net
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CREATE_TOPICS: "movies:1:1"
      KAFKA_ZOOKEEPER_CONNECT: streamx-zookeeper:2181
