version: '3.7'

networks:
  streamx-net:
    driver: bridge

services:

  streamx-zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    ports:
      - "2181:2181"
    networks:
      - streamx-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  streamx-kafka:
    image: confluentinc/cp-kafka:5.0.0
    ports:
      - "9092:9092"
    links:
      - streamx-zookeeper
    networks:
      - streamx-net
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: streamx-zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
